"""arspe_py 类型存根（编译模块无内省源，IDE/类型检查请使用本文件）。"""

from typing import Any

import numpy as np
from numpy.typing import NDArray

__version__: str
CONST_1240: float              # λ(nm)·E(eV) ≈ 1239.84；数组换算用 CONST_1240 / wl

class ArspeError(Exception): ...
class ParseError(ArspeError): ...
class UnsupportedFormatError(ArspeError): ...
class StretchError(ArspeError): ...

class Calibration:
    detector_angle_cal: float
    focal_length_cal: float
    inclusion_angle_cal: float
    detector_angle_exp: float
    focal_length_exp: float
    inclusion_angle_exp: float
    def __repr__(self) -> str: ...

class SpeData:
    @property
    def width(self) -> int: ...          # 波长列数（y 方向）
    @property
    def height(self) -> int: ...         # 角度行数（x 方向）
    @property
    def frame_count(self) -> int: ...
    @property
    def frames(self) -> NDArray[np.float64]: ...        # (n_frames, height, width)
    @property
    def wavelength(self) -> NDArray[np.float64] | None: ...
    @property
    def min_max(self) -> NDArray[np.float64]: ...       # (n_frames, 2)
    @property
    def calibration(self) -> Calibration: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def save_csv(
        self, path: str | bytes, frame_index: int | None = None, header: bool | None = None
    ) -> None: ...
    def __repr__(self) -> str: ...

def open_file(path: str | bytes) -> SpeData: ...
def parse_spe(data: bytes) -> SpeData: ...
def parse_text(text: str) -> SpeData: ...
def stretch(
    spe: SpeData, ev_mode: bool, x_mode: str, tan_min: float, tan_max: float
) -> SpeData: ...
def lambda_to_energy(lambda_nm: float) -> float: ...
def energy_to_lambda(energy_ev: float) -> float: ...
def tan_to_angle(tan_theta: float) -> float: ...
def angle_to_tan(angle_deg: float) -> float: ...
def tan_to_k(tan_theta: float, lambda_nm: float) -> float: ...
def k_to_tan(k_um_inv: float, lambda_nm: float) -> float: ...

class YRange:
    def __init__(self, min_lambda: float, max_lambda: float) -> None: ...
    @staticmethod
    def from_wavelength(wavelength: list[float] | NDArray[np.float64]) -> YRange: ...
    @property
    def min_lambda(self) -> float: ...
    @min_lambda.setter
    def min_lambda(self, val: float) -> None: ...
    @property
    def max_lambda(self) -> float: ...
    @max_lambda.setter
    def max_lambda(self, val: float) -> None: ...
    @property
    def min_energy(self) -> float: ...
    @min_energy.setter
    def min_energy(self, val: float) -> None: ...
    @property
    def max_energy(self) -> float: ...
    @max_energy.setter
    def max_energy(self, val: float) -> None: ...
    @property
    def band_width(self) -> float: ...
    @property
    def band_gap(self) -> float: ...
    def index_range_of_lambda_in(self, range: YRange, length: float) -> tuple[int, int]: ...
    def index_range_of_energy_in(self, range: YRange, length: float) -> tuple[int, int]: ...
    def __repr__(self) -> str: ...

class XRange:
    def __init__(
        self, na: float, lambda: float, binding: tuple[float, float, float] | None = None
    ) -> None: ...
    @property
    def min_tan(self) -> float: ...
    @min_tan.setter
    def min_tan(self, val: float) -> None: ...
    @property
    def max_tan(self) -> float: ...
    @max_tan.setter
    def max_tan(self, val: float) -> None: ...
    @property
    def min_angle(self) -> float: ...
    @min_angle.setter
    def min_angle(self, val: float) -> None: ...
    @property
    def max_angle(self) -> float: ...
    @max_angle.setter
    def max_angle(self, val: float) -> None: ...
    @property
    def min_k(self) -> float: ...
    @min_k.setter
    def min_k(self, val: float) -> None: ...
    @property
    def max_k(self) -> float: ...
    @max_k.setter
    def max_k(self, val: float) -> None: ...
    def index_range_of_tan_in(self, range: XRange, length: float) -> tuple[int, int]: ...
    def index_range_of_angle_in(self, range: XRange, length: float) -> tuple[int, int]: ...
    def index_range_of_k_in(self, range: XRange, length: float) -> tuple[int, int]: ...
    def __repr__(self) -> str: ...
